### ISSUE TITLE
There are two combinations of A1 and Topic that give one word without buttons

### ISSUE THREAD

**Issue by lajanda** [bast/twirll-prototype#21]
The buttons for Next word, Previous word, and translation are missing for these two. Please see the attached screen shots. The combinations are A1 + животные/растения and A1 + погода.
![screen shot 2019-01-25 at 18 49 10](https://user-images.githubusercontent.com/26918586/51763518-1a1ff100-20d3-11e9-9f9e-2e972f8016d0.png)
![screen shot 2019-01-25 at 18 52 57](https://user-images.githubusercontent.com/26918586/51763519-1ab88780-20d3-11e9-8163-43c1abdc5d09.png)

**Comment by bast** [comment]
I think this problem is gone. It might have been a problem on the data side. Can you please check again whether this problem is still there?

**Comment by lajanda** [comment]
This seems to be fixed.
