### ISSUE TITLE
Can we have a “All Levels” option under “Level”?

### ISSUE THREAD

**Issue by lajanda** [bast/twirll-prototype#25]
It would be nice to have an option to find all words in all levels for a given topic, analysis or in the dictionary.

**Comment by bast** [comment]
Sure - this sounds doable. I will add this soon.

**Comment by bast** [comment]
So just to make sure I understood right - the goal is to have an extra entry under "Level" which will be "all levels" but the rest of the interface and browsing will be the same?

**Comment by lajanda** [comment]
Yes, is that possible? I think it would be a useful function.

**Comment by bast** [comment]
Yes I will add this.
