### ISSUE TITLE
Error in highlighting

### ISSUE THREAD

**Issue by lajanda** [bast/twirll-prototype#27]
![Screen Shot 2019-05-19 at 10 03 47](https://user-images.githubusercontent.com/26918586/58630629-485f4880-82e0-11e9-9224-cb134f344089.png)
Please see attached screenshot: There is an item here that is not highlighted but should be: книги

**Comment by bast** [comment]
In the data the "Form" is "преподавателя", not "книги". In other words I think this is not correct in the data. But I might have misunderstood. Can you please confirm this? In this case we can close this here.

**Comment by lajanda** [comment]
Dear Radovan,
       Thanks for spotting that. That is a real error. We need to replace that sentence altogether.
Zhenya, can you take care of this? It is in Zhenya A1, line 396. The problem is that the form we are looking for is the Genitive Singular преподавателя, but this sentence gives us the Nominative Singular.
       --laura
