### ISSUE TITLE
Use of googlesheets vs. github for content development

### ISSUE THREAD

**Issue by lajanda** [bast/twirll-prototype#30]
This isn't exactly an issue, but a question. This is about how we currently use googlesheets and a question of how we could do this in github.
Editing the content of the SMARTool is a big job, and we have been using a system of coloring in the cells to keep track of that. We color in green the cells that have been checked and ok'd, violet for cells where I have made corrections, red for cells where there is a problem that needs to be fixed, and yellow for a problem that has been fixed but still needs to be checked and ok'd. The colors make it easy to find where we are in the process and to find the places where we need to go back and fix things. 
Does github allow one to color in cells in a spreadsheet? If so, then we should go entirely over to adding content in github. If not, we should either keep the dual system of googlesheets and github, or come up with some other way to keep track of the editing process in github.

**Comment by bast** [comment]
On GitHub side we store data in CSV files. The GitHub way of doing this would be that all changes are submitted as pull requests (in other words for review), and not pushed directly to the "production" data. Merging a pull request would mean approving the changes. In the pull request you could request corrections/changes. In other words you can have discussions in a pull request discussion thread. At some point I could give you a demo. When working with pull requests I recommend to create new Git branches for each new change. I can imagine that there is a lot of jargon here - sorry for that.

**Comment by lajanda** [comment]
Thanks, Radovan. I’m afraid I understand almost nothing of what you wrote. That’s ok, it’s my fault for lacking proficiency. But I will be happy to learn.  :^)

**Comment by bast** [comment]
Directly pushing changes = changing the document directly.

Pull request = change proposal with peer review possibility.

I recommend that all changes to code and data are submitted indirectly as change proposals instead of changed directly. During the peer review process you can suggest and track changes.

**Comment by bast** [comment]
We have discussed this today and concluded that it's probably good to keep the current workflow.
