### ISSUE TITLE
Excerpting the SMARTool

### ISSUE THREAD

**Issue by lajanda** [bast/twirll-prototype#34]
We would like to excerpt some portions of the SMARTool for specific lessons for students.

We are in the process of developing a first-semester course in Russian that will be entirely online, called Russisk uten permer. Attached is a file with a plan for this course where the vocabulary is based upon the words in the A1 portion of the SMARTool. The left-most column is the number of each lesson, and in the middle column called Gloser fra SMARTool are the words for each lesson. There are 35 lessons, but two of them do not have vocabulary because they are review lessons (14 and 35). So there are 33 sets of words here that we would like to have excerpted.

We would like to get 33 links to these excerpts, such that each excerpt is its own entity. The excerpts would need to give the possibility of toggling through the given set of words (using the green forward and backward arrows), plus the options of getting translations and voice synthesis, and search through dictionary (which will be very small). It would also be nice to preserve the function that searches by analysis. The search by topic function is probably less useful for such small excerpts. Since all of these words are in A1 and these are excerpts, we do not need (or want) to ask the user to filter by Level.

If at all possible, we would like to get the excerpts for lessons 27, 28, and 29 first, and preferably by Dec 1 2019, since we want to create a pilot that we can test out on our current students.

Does this seem doable?

Is the format in the attached document problematic? If so, I can provide a different format, just say what it is.

--laura

[Navigator Russisk uten permer 29_10_19.docx](https://github.com/smartool/smartool/files/3815011/Navigator.Russisk.uten.permer.29_10_19.docx)

**Comment by bast** [comment]
It is possible to portion the data into lessons but how will the app know which words/sentences belong to which lessons? Will there be an extra column?

For me doing major feature changes this month or even before new year is extremely challenging since I am almost non-stop traveling until then.

**Comment by lajanda** [comment]
Oh, I am sorry Radovan.
[By the way, I am working intensively with the administration trying to get a second programmer for Giellatekno, since Chiara is overwhelmed, and I hope that we will have someone in place and after that we won’t have to bother you.]
I will meanwhile look again at our plan for the columns that we have agreed to implement on Jan 15 and select a column to the right of all those to designate as the “Lesson” column and add in all the lesson numbers for each word and sentence so that it will be easy to implement. We can look into this after you are back after the new year.
                Safe travels!!
                --laura

**Comment by bast** [comment]
Notes to self:
- create a new page/repo (min-russiske-reise) where everything behaves the same but instead of levels we select lessons
- data entries without lesson number are then "invisible" to that page and not there
- replace "SMARTool for English-speaking learners of Russian" by "SMARTool for Min russiske reise"

**Comment by bast** [comment]
This is now hopefully done: https://smartool.github.io/min-russiske-reise/
