### ISSUE TITLE
Maybe add a banner to identify the target and user languages?

### ISSUE THREAD

**Issue by lajanda** [bast/twirll-prototype#35]
Now that SMARTool is to become a family rather than just being a tool for English-speaking learners of Russian, perhaps we need to modify the site so that it identifies which SMARTool one is located at? Perhaps a banner that would say something like:
SMARTool for English-speaking learners of Russian
or in its generic version:
SMARTool for [User language]-speaking learners of [Target language].

**Comment by bast** [comment]
Good idea.
