### ISSUE TITLE
Claim of problem with audio

### ISSUE THREAD

**Issue by lajanda** [bast/twirll-prototype#37]
I received the following message on the facebook page I set up for the SMARTool from someone named Lars Aronsson:
“The sound (green speaker icon) works for a male voice of the phrase “Ване двадцать пять лет”, but for no other phrases. (I'm using the Firefox browser on Linux.)”
I don't have any way to verify whether there is really such a problem myself, I am not a Linux user, nor a Firefox user.
--laura

**Comment by bast** [comment]
I have moved the issue. The other place was discontinued. Which sentence number is it?

**Comment by lajanda** [comment]
Oh, I am so sorry. Now I see that I should have put it here, right? https://github.com/smartool/data-rus-eng
The sentence that Lars Aronsson refers to is the first one in the whole database: ID number 1

**Comment by bast** [comment]
I just tried it on Linux and Firefox and unfortunately cannot reproduce this. But the problem might have been there.
