### ISSUE TITLE
the function with the question mark to get grammatical parse is not working

### ISSUE THREAD

**Issue by lajanda** [bast/twirll-prototype#42]
I have gotten the following message from a colleague:
Takket være en melding av Helene Andreassen på Facebook oppdaget jeg at dere har laget SMARTool. Det ser kjempeflott ut!
Og bra at det er med lyd. Men jeg får ikke lydfilene til å virke, og heller ikke det som skal ligge under spørsmålstegnet ved siden av hver setning. Jeg har prøvd ulike nettlesere. Gjør jeg noe feil?
I explained to her that we are working with the voice synthesizer site to get the sound fixed. But the problem with the question mark (which we had before, if I remember correctly) is back -- when you mouse over, nothing happens.

**Comment by bast** [comment]
Can you reproduce it? Because I unfortunately (or fortunately?) cannot. On which browser is this not working?

**Comment by lajanda** [comment]
I should have told you the browser of course. But now I tried it again in both Chrome and Safari and it seems to work. It takes a bit of careful movement, but now it does seem to work. And the female voice seems to work too though the male voice does not.

**Comment by bast** [comment]
About the voices, I have written them but still wait for answer but I will try again.

**Comment by bast** [comment]
Text to voice restored (still need to fix min-russiske-reise).
